[server]
bind = "*" # Use * for all interfaces. UDP and LLMNR broadcast servers will always listen on all interfaces however.
webgui_port = 8080
# Users who use the official HDHomerun apps will want all of these enabled.
# If you just want something for your Plex server, you just want the WebGUI and HTTPStream servers enabled.
enable_webgui = true # Web interface for managing this instance
enable_httpstream = true # HTTP Stream interface (:5004/auto/v14.1)
enable_broadcast = true # UDP broadcast client for detecting devices
enable_control = true # TCP control port for managing things like channels

[device]
# hwmodel + model: https://www.silicondust.com/support/linux/
hwmodel = "HDHR5-4US"
model = "hdhomerun5_atsc"
firmware = "20220203" # https://www.silicondust.com/support/downloads/firmware-changelog/
device_id = "107C21C8" # Still needs reverse engineering.